# Generated by Django 6.0.2 on 2026-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='domicilios_mes',
            field=models.PositiveIntegerField(default=0, verbose_name='Domicilios realizados este mes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mes_ultimo_domicilio',
            field=models.PositiveIntegerField(default=0, verbose_name='Mes del último domicilio'),
        ),
    ]
