# Generated by Django 6.0.2 on 2026-03-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_carta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
    ]
