# Generated by Django 6.0.2 on 2026-03-11 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('TIENDA', 'Recoger en tienda'), ('DOMICILIO', 'Entrega a domicilio')], default='TIENDA', max_length=10, verbose_name='Tipo de entrega')),
                ('direccion_entrega', models.TextField(blank=True, null=True, verbose_name='Dirección de entrega (solo para domicilio)')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, verbose_name='Teléfono de contacto')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total del pedido')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15, verbose_name='Estado del pedido')),
                ('resultado_dado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Resultado del dado dinámico')),
                ('recompensa_dado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recompensa del dado')),
                ('aplica_papa_cumpleañera', models.BooleanField(default=False, verbose_name='Aplica Papa Cumpleañera (pedido gratis)')),
                ('aplica_papa_oclock', models.BooleanField(default=False, verbose_name="Aplica Papa O'clock (envío gratis)")),
                ('aplica_4x3', models.BooleanField(default=False, verbose_name='Aplica 4x3 (domicilio gratis)')),
                ('descuento_aplicado', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Descuento aplicado')),
                ('costo_envio', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega estimada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Subtotal')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
    ]
