# Generated by Django 6.0.2 on 2026-03-13 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('DADO_DINAMICO', 'Dado Dinámico'), ('PAPA_CUMPLEANERA', 'Papa Cumpleañera'), ('PAPA_OCLOCK', 'Papa Oclock'), ('PAPA_LOVERS_4X3', 'Papa Lovers 4x3')], max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🎁', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('valor_descuento', models.DecimalField(decimal_places=0, default=0, help_text='Porcentaje de descuento', max_digits=5)),
                ('monto_maximo', models.DecimalField(decimal_places=0, default=0, help_text='Monto máximo del beneficio', max_digits=10)),
            ],
            options={
                'verbose_name': 'Programa de Fidelización',
                'verbose_name_plural': 'Programas de Fidelización',
            },
        ),
        migrations.CreateModel(
            name='ResultadoFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=100)),
                ('recompensa', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_fidelizacion', to='app_pedidos.pedido')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='app_fidelizacion.programafidelizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_fidelizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de Fidelización',
                'verbose_name_plural': 'Resultados de Fidelización',
            },
        ),
    ]
