# Generated by Django 6.0.3 on 2026-03-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fidelizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programafidelizacion',
            name='cantidad_minima_pedidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
